apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-sales-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ai-sales-tool.devfaihui.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-sales-web-service
            port:
              number: 80
